Django/Django-modelfom/accounts/urls.py
from django.urls import path
from . import views

# app_name은 왜 쓸까요?
# 우리는 기본적으로 URL을 모두 변수화해서 쓰고 있음
# Template, View에서 직접 '/accounts/' X
# app_name과 path 이름으로

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    # path('accounts/',views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/", views.detail, name="detail"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
]

Django/Django-modelfom/articles/urls.py
# URL설정을 app 단위로!
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # http://127.0.0.1:8000/articles/
    path("", views.index, name="index"),
    # http://127.0.0.1:8000/articles/new/
    # path('new/', views.new, name='new'),
    # http://127.0.0.1:8000/articles/create/
    path("create/", views.create, name="create"),
    # http://127.0.0.1:8000/articles/1/ : 1번글
    # http://127.0.0.1:8000/articles/3/ : 3번글
    path("<int:pk>/", views.detail, name="detail"),
    # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
    # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:article_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/like/", views.like, name="like"),
]

Django/Django-modelfom/practice_1011/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.root),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("martor/", include("martor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Django-modelfom/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    # https://docs.djangoproject.com/en/4.1/ref/models/fields/#recursive-relationships
    # https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ManyToManyField.symmetrical
    # A가 B를 팔로잉, 이 것은 서로 친구 X(symmetrical=False)
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

Django/Django-modelfom/articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from django.conf import settings

# Create your models here.
"""
게시판 기능 
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/시간)
"""
# 1. 모델 설계 (DB 스키마 설계)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

Django/Django-modelfom/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# from .models import User
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )


class CustomUserChangeForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )
        #'__all__'

Django/Django-modelfom/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import User

from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    users = User.objects.all()
    # Template에 전달한다.
    context = {"users": users}
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            auth_login(request, user)  # 로그인
            return redirect("articles:index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {"user": user}
    return render(request, "accounts/detail.html", context)


def login(request):
    if request.method == "POST":
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            # http://127.0.0.1:8000/accounts/login/?next=/articles/1/update/
            # request.GET.get('next') : /articles/1/update/
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 하였습니다.")
    return redirect("articles:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)


@login_required
def follow(request, pk):
    # 프로필에 해당하는 유저를 로그인한 유저가!
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user == user:
        messages.warning(request, "스스로 팔로우 할 수 없습니다.")
        return redirect("accounts:detail", pk)
    if request.user in user.followers.all():
        # (이미) 팔로우 상태이면, '팔로우 취소'버튼을 누르면 삭제 (remove)
        user.followers.remove(request.user)
    else:
        # 팔로우 상태가 아니면, '팔로우'를 누르면 추가 (add)
        user.followers.add(request.user)
    return redirect("accounts:detail", pk)

Django/Django-modelfom/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ user.username }}님의 프로필</h1>
<table class="table text-center align-middle">
    <thead>
        <th>ID</th>
        <th>username</th>
        <th>e-mail</th>
        <th>성</th>
        <th>이름</th>
        <th>생성 날짜</th>
        <th>최근 로그인</th>
        <th>회원 정보 수정</th>
    </thead>
    <tbody>
        <tr>
            <td>{{user.id}}</td>
            <td>{{ user.username }}</td>
            <td>{{user.email}}</td>
            <td>{{user.last_name}}</td>
            <td>{{user.first_name}}</td>
            <td>{{user.date_joined}}</td>
            <td>{{user.last_login}}</td>
            <td><a href="{% url 'accounts:update' %}">수정</a></td>
        </tr>
    </tbody>
</table>
<h1>{{ user.username }}님의 프로필</h1>
<p>{{ user.email }} | {{ user.full_name }}</p>
<p>팔로우 : {{ user.followings.count }} | 팔로워 : {{ user.followers.count }}</p>
{% if request.user != user %}
<a href="{% url 'accounts:follow' user.pk %}">
    {% if request.user in user.followers.all %}
    팔로우 취소
    {% else %}
    팔로우
    {% endif %}
</a>
{% endif %}
<div class="row">
    <div class="col-6">
        <h3>작성한 글</h3>
        <p class="text-muted">{{ user.article_set.count }}개를 작성하였습니다.</p>
        {% for article in user.article_set.all %}
        <p>
            {{ forloop.counter }}
            <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
        </p>
        {% endfor %}
    </div>
    <div class="col-6">
        <h3>작성한 댓글</h3>
        <p class="text-muted">{{ user.comment_set.count }}개를 작성하였습니다.</p>
        {% for comment in user.comment_set.all %}
        <p>
            {{ forloop.counter }}
            <a href="{% url 'articles:detail' comment.article_id %}">{{ comment.content }}</a>
        </p>
        {% endfor %}
    </div>
    <div class="col-6">
        <h3>좋아요 누른 글</h3>
        <p class="text-muted">{{ user.like_articles.count }}개를 작성하였습니다.</p>
        {% for article in user.like_articles.all %}
        <p>
            {{ forloop.counter }}
            <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
        </p>
        {% endfor %}
    </div>
</div>
{% endblock body %}

Django/Django-modelfom/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<h1>회원정보</h1>
<table class="table text-center align-middle">
    <thead>
        <th>ID</th>
        <th>username</th>
        <th>e-mail</th>
        <th>생성 날짜</th>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{user.id}}</td>
            <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
            <td>{{user.email}}</td>
            <td>{{user.date_joined}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<hr>
{% endblock %}

Django/Django-modelfom/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock body %}

Django/Django-modelfom/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>회원가입</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>

{% endblock body %}

Django/Django-modelfom/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>프로필 업데이트</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock body %}