Django/Django-Todolist/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

Django/Django-Todolist/crud/todos/urls.py
from django.urls import path
from . import views

app_name = "todos"
urlpatterns = [
    path("", views.index, name="index"),
    # path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("delete/<int:todo_pk>", views.delete, name="delete"),
    path(
        "completed_toggle/<int:todo_pk>",
        views.completed_toggle,
        name="completed_toggle",
    ),
    path("edit/<int:todo_pk>", views.edit, name="edit"),
    ##테스트 출력용
    path("editUpdate/<int:pk>", views.editUpdate, name="editUpdate"),
    path("hello", views.hello, name="hello"),
    # path("priority_filter/", views.priority_filter, name="priority_filter"),
]

Django/Django-Todolist/crud/todos/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

Django/Django-Todolist/crud/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    _todos = Todo.objects.all()
    context = {"todos": _todos}

    return render(request, "todos/index.html", context)


def create(request):

    # 1. parameter로 날라온 데이터를 받아서
    content = request.GET.get("content_")
    priority = request.GET.get("priority_")
    deadline = request.GET.get("deadline_")

    # 2. DB에 저장
    Todo.objects.create(content=content, priority=priority, deadline=deadline)

    context = {"content": content, "priority": priority, "deadline": deadline}

    return redirect("todos:index")


def delete(request, todo_pk):
    # pk에 해당하는 글 삭제
    Todo.objects.get(id=todo_pk).delete()

    return redirect("todos:index")


def completed_toggle(request, todo_pk):
    obj = Todo.objects.get(id=todo_pk)
    obj.completed = not obj.completed
    obj.save()
    return redirect("todos:index")


def edit(request, todo_pk):

    return redirect("todos:index")


def editUpdate(request, pk):
    todos = Todo.objects.get(id=pk)
    todos.content = request.GET.get("content_")
    todos.priority = request.GET.get("priority_")
    todos.deadline = request.GET.get("deadline_")
    todos.save()

    return redirect("todos:index")


def hello(request):
    # 대강의 필터 구현
    data = []
    for obj in Todo.objects.filter(priority=5):
        data.append(obj)
    context = {"todos": data}
    return render(request, "todos/hello.html", context)

    # return render(request, "todos/hello.html")


# def priority_filter(request):
#     todos = []
#     for obj in Todo.objects.filter(priority=5):
#         todos.append(obj)
#     context = {"todos": todos}
#     return render(request, "todos:index")

Django/Django-Todolist/crud/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</head>

<body>

  {% block content %}

  {% endblock %}

</body>

</html>

Django/Django-Todolist/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</head>

<body>

  {% block content %}

  {% endblock %}

</body>

</html>

Django/Django-Todolist/crud/todos/templates/todos/filter.html
{% extends 'base.html' %}

{%block content%}

{%endblock%}

Django/Django-Todolist/crud/todos/templates/todos/hello.html
{% extends 'base.html' %}

{%block content%}
<div class="container shadow-lg p-5 mt-5 mb-5 bg-body rounded-5" style="min-width: 770px">
    <div class="text text-center">해야할 일</div>
    <!-- 입력 폼 -->
    <form action="{% url 'todos:create' %}">
        <div class="input-group mb-3">
            <span class="input-group-text">할 일</span>
            <div class="form-floating">
                <input name="content_" type="text" class="form-control" id="floatingInputGroup1">
                <label for="floatingInputGroup1" class="text-secondary">What to do</label>
            </div>
        </div>
        <!-- 우선순위 선택 -->
        <div class="input-group mb-3">
            <span class="input-group-text">우선순위</span>
            <div class="form-floating">
                <select name="priority_" class="form-select" id="floatingSelect"
                    aria-label="Floating label select example">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3" selected>3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <label for="floatingSelect">우선순위 선택</label>
            </div>
        </div>
        <!-- 데드라인 설정 -->
        <div class="input-group mb-3">
            <span class="input-group-text">마감기한</span>
            <div class="form-floating">
                <input name="deadline_" type="date" class="form-control" id="floatingInputGroup1">
                <label for="floatingInputGroup1">Deadline</label>
            </div>
        </div>
        <!-- 할 일 추가 -->
        <div class="mt-5">
            <input class="w-100 btn btn-outline-primary" type="submit">
        </div>
    </form>




    <table class="table text-center align-middle">
        <thead>
            <th>ID</th>
            <th>우선 순위</th>
            <th>할 일 내용</th>
            <th>생성 날짜</th>
            <th>마감 기한</th>
            <th>진행 상태</th>
            <th>상태 변경</th>
            <th>수정</th>
            <th>삭제</th>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr>

                <td>{{todo.id}}</td>
                <td>{{todo.priority}}</td>
                <td>
                    {% if todo.completed == True %}
                    <div class="text-decoration-line-through">{{todo.content}}</div>
                    {% else %}
                    {{todo.content}}
                    {% endif %}
                </td>
                <td>{{todo.created_at |date:'Y년 m월 d일'}}</td>
                <td>{{todo.deadline |date:'Y년 m월 d일' }}</td>
                <td>
                    {% if todo.completed == True %}
                    <div class="badge bg-primary text-wrap"> 완료</div>
                    {% else %}
                    <div class="badge bg-secondary text-wrap">미완료</div>

                    {% endif %}

                </td>
                <td>
                    <a href="{% url 'todos:completed_toggle' todo.pk %}">
                        {% if todo.completed == True %}
                        <input type="submit" class="btn btn-warning" value="미완료">
                        {% else %}
                        <input type="submit" class="btn btn-success" value="완료">
                        {% endif %}
                    </a>
                </td>
                <td>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#modal{{todo.id}}">
                        수정
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="modal{{todo.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">수정</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'todos:editUpdate' todo.pk %}">
                                        {# 할 일 #}
                                        <div class="input-group mb-3">
                                            <span class="bg-white fw-light input-group-text" id="todolist">할 일</span>
                                            <input value="{{ todo.content }}" type="text" name="content_"
                                                class="form-control" aria-label="todo" aria-describedby="todolist"
                                                maxlength="80">
                                        </div>
                                        {# 우선 순위 #}
                                        <div class="input-group mb-3">
                                            <label class="bg-white fw-light input-group-text"
                                                for="inputGroupSelect01">우선 순위</label>
                                            <select class="form-select" id="inputGroupSelect01" name="priority_">
                                                <option value="{{ todo.priority }}" selected hidden>{{ todo.priority }}
                                                </option>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                        {# 마감 기한 #}
                                        <div class="input-group mb-3">
                                            <span class="bg-white fw-light input-group-text" id="basic-addon1">마감
                                                기한</span>
                                            <input value="{{todo.deadline|date:'Y-m-d'}}" type="date"
                                                class="form-control" name="deadline_" placeholder="Username"
                                                aria-label="Username" aria-describedby="basic-addon1">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">수정 완료</button>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                    </a>
                </td>
                <td>
                    <a href="{% url 'todos:delete' todo.pk %}">
                        <input type="submit" class="btn btn-danger" value="삭제">
                    </a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{%endblock%}

Django/Django-Todolist/crud/todos/templates/todos/index.html
{% extends 'base.html' %}

{%block content%}
<div class="container shadow-lg p-5 mt-5 mb-5 bg-body rounded-5" style="min-width: 770px">
    <div class="text text-center">해야할 일</div>
    <!-- 입력 폼 -->
    <form action="{% url 'todos:create' %}">
        <div class="input-group mb-3">
            <span class="input-group-text">할 일</span>
            <div class="form-floating">
                <input name="content_" type="text" class="form-control" id="floatingInputGroup1">
                <label for="floatingInputGroup1" class="text-secondary">What to do</label>
            </div>
        </div>
        <!-- 우선순위 선택 -->
        <div class="input-group mb-3">
            <span class="input-group-text">우선순위</span>
            <div class="form-floating">
                <select name="priority_" class="form-select" id="floatingSelect"
                    aria-label="Floating label select example">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3" selected>3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <label for="floatingSelect">우선순위 선택</label>
            </div>
        </div>
        <!-- 데드라인 설정 -->
        <div class="input-group mb-3">
            <span class="input-group-text">마감기한</span>
            <div class="form-floating">
                <input name="deadline_" type="date" class="form-control" id="floatingInputGroup1">
                <label for="floatingInputGroup1">Deadline</label>
            </div>
        </div>
        <!-- 할 일 추가 -->
        <div class="mt-5">
            <input class="w-100 btn btn-outline-primary" type="submit">
        </div>
    </form>




    <table class="table text-center align-middle">
        <thead>
            <th>ID</th>
            <th>우선 순위</th>
            <th>할 일 내용</th>
            <th>생성 날짜</th>
            <th>마감 기한</th>
            <th>진행 상태</th>
            <th>상태 변경</th>
            <th>수정</th>
            <th>삭제</th>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr>

                <td>{{todo.id}}</td>
                <td>{{todo.priority}}</td>
                <td>
                    {% if todo.completed == True %}
                    <div class="text-decoration-line-through">{{todo.content}}</div>
                    {% else %}
                    {{todo.content}}
                    {% endif %}
                </td>
                <td>{{todo.created_at |date:'Y년 m월 d일'}}</td>
                <td>{{todo.deadline |date:'Y년 m월 d일' }}</td>
                <td>
                    {% if todo.completed == True %}
                    <div class="badge bg-primary text-wrap"> 완료</div>
                    {% else %}
                    <div class="badge bg-secondary text-wrap">미완료</div>

                    {% endif %}

                </td>
                <td>
                    <a href="{% url 'todos:completed_toggle' todo.pk %}">
                        {% if todo.completed == True %}
                        <input type="submit" class="btn btn-warning" value="미완료">
                        {% else %}
                        <input type="submit" class="btn btn-success" value="완료">
                        {% endif %}
                    </a>
                </td>
                <td>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#modal{{todo.id}}">
                        수정
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="modal{{todo.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">수정</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'todos:editUpdate' todo.pk %}">
                                        {# 할 일 #}
                                        <div class="input-group mb-3">
                                            <span class="bg-white fw-light input-group-text" id="todolist">할 일</span>
                                            <input value="{{ todo.content }}" type="text" name="content_"
                                                class="form-control" aria-label="todo" aria-describedby="todolist"
                                                maxlength="80">
                                        </div>
                                        {# 우선 순위 #}
                                        <div class="input-group mb-3">
                                            <label class="bg-white fw-light input-group-text"
                                                for="inputGroupSelect01">우선 순위</label>
                                            <select class="form-select" id="inputGroupSelect01" name="priority_">
                                                <option value="{{ todo.priority }}" selected hidden>{{ todo.priority }}
                                                </option>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                        {# 마감 기한 #}
                                        <div class="input-group mb-3">
                                            <span class="bg-white fw-light input-group-text" id="basic-addon1">마감
                                                기한</span>
                                            <input value="{{todo.deadline|date:'Y-m-d'}}" type="date"
                                                class="form-control" name="deadline_" placeholder="Username"
                                                aria-label="Username" aria-describedby="basic-addon1">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">수정 완료</button>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                    </a>
                </td>
                <td>
                    <a href="{% url 'todos:delete' todo.pk %}">
                        <input type="submit" class="btn btn-danger" value="삭제">
                    </a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>

</div>
{%endblock%}