Django/Django-modelfom/accounts/urls.py
from django.urls import path
from . import views

# app_name은 왜 쓸까요?
# 우리는 기본적으로 URL을 모두 변수화해서 쓰고 있음
# Template, View에서 직접 '/accounts/' X
# app_name과 path 이름으로

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    # path('accounts/',views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/", views.detail, name="detail"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
]

Django/Django-modelfom/articles/urls.py
# URL설정을 app 단위로!
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # http://127.0.0.1:8000/articles/
    path("", views.index, name="index"),
    # http://127.0.0.1:8000/articles/new/
    # path('new/', views.new, name='new'),
    # http://127.0.0.1:8000/articles/create/
    path("create/", views.create, name="create"),
    # http://127.0.0.1:8000/articles/1/ : 1번글
    # http://127.0.0.1:8000/articles/3/ : 3번글
    path("<int:pk>/", views.detail, name="detail"),
    # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
    # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:article_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/like/", views.like, name="like"),
]

Django/Django-modelfom/practice_1011/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.root),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("martor/", include("martor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Django-modelfom/practice_1011/views.py
from django.shortcuts import render


def root(request):
    return render(request, "root.html")

Django/Django-modelfom/practice_1011/templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'articles:index' %}">Home</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup'%}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="container my-5">
        {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
</body>

</html>

Django/Django-modelfom/practice_1011/templates/root.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1 class="text text-center">메인 페이지</h1>
{% endblock %}